# PANDAS TASK

In [748]:
df=pd.read_csv(r"C:\Users\SANITHA\Documents\data analytics\review\files\employee_data.csv")

In [749]:
import pandas as pd

# SECTION A: DATA EXPLORATION

## QS 1

In [750]:
df

,ID,Name,Department,City,Job Role,Salary,Exp_Yrs,Rating
0,1,Arun Kumar,Sales,Calicut,Executive,28000.0,3,4.2
1,2,Priya Nair,IT,Kochi,Developer,45000.0,5,4.7
2,3,Rahul Menon,HR,Calicut,Manager,38000.0,7,NaN
3,4,Sneha Das,Sales,Thrissur,Executive,29000.0,2,3.9
4,5,Vijay S,IT,Kochi,Developer,47000.0,6,4.5
...,...,...,...,...,...,...,...,...
58,59,Joseph Kumar,Finance,Thrissur,Senior Analyst,38500.0,7,4.6
59,60,Sreeja Devi,Finance,Calicut,Senior Analyst,48000.0,11,4.3
60,61,Priya Nair,IT,Kochi,Developer,45000.0,5,4.7
61,62,Anoop M,IT,Calicut,Developer,43000.0,5,4.3
62,63,Jishnu Devi,HR,Thrissur,Recruiter,26000.0,10,4.4

In [751]:
df.head()

   ID         Name Department      City   Job Role   Salary  Exp_Yrs  Rating
0   1   Arun Kumar      Sales   Calicut  Executive  28000.0        3     4.2
1   2   Priya Nair         IT     Kochi  Developer  45000.0        5     4.7
2   3  Rahul Menon         HR   Calicut    Manager  38000.0        7     NaN
3   4    Sneha Das      Sales  Thrissur  Executive  29000.0        2     3.9
4   5      Vijay S         IT     Kochi  Developer  47000.0        6     4.5

## QS 2

In [752]:
df.shape

(63, 8)

## QS 3

In [753]:
df.columns

Index(['ID', 'Name', 'Department', 'City', 'Job Role', 'Salary', 'Exp_Yrs',
       'Rating'],
      dtype='object')

In [754]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 63 entries, 0 to 62
Data columns (total 8 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   ID          63 non-null     int64
 1   Name        58 non-null     object
 2   Department  63 non-null     object
 3   City        57 non-null     object
 4   Job Role    63 non-null     object
 5   Salary      62 non-null     float64
 6   Exp_Yrs     63 non-null     int64
 7   Rating      58 non-null     float64
dtypes: float64(2), int64(2), object(4)
memory usage: 4.1+ KB

In [755]:
df.isnull().sum()

ID            0
Name          5
Department    0
City          6
Job Role      0
Salary        1
Exp_Yrs       0
Rating        5
dtype: int64

## QS 4

In [756]:
df.describe()

              ID        Salary    Exp_Yrs     Rating
count  63.000000     62.000000  63.000000  58.000000
mean   32.000000  38822.580645   6.063492   4.194828
std    18.330303  12657.239480   3.267005   0.455925
min     1.000000  25000.000000   1.000000   3.400000
25%    16.500000  28000.000000   3.000000   3.800000
50%    32.000000  34000.000000   6.000000   4.200000
75%    47.500000  46500.000000   9.000000   4.600000
max    63.000000  65500.000000  12.000000   4.900000

In [757]:
df["Salary"].mean()

np.float64(38822.58064516129)

## QS 5

In [758]:
df.value_counts()

ID  Name                Department  City      Job Role          Salary   Exp_Yrs  Rating
1   Arun Kumar          Sales       Calicut   Executive         28000.0  3        4.2       1
52  Naveen C            IT          Calicut   Lead              63500.0  6        4.6       1
39  Naveen K            Finance     Kannur    Analyst           34000.0  8        4.6       1
42  Sneha Nair          HR          Palakkad  Manager           29000.0  1        4.8       1
43  Ajay Das            IT          Palakkad  Lead              58500.0  10       3.5       1
44  Jishnu Devi         HR          Thrissur  Executive         32000.0  7        3.6       1
45  Sajith Mathew       Sales       Palakkad  Executive         26000.0  9        3.7       1
46  Nimisha R           HR          Kannur    Recruiter         33500.0  10       4.9       1
47  Fathima K           Sales       Calicut   Executive         33500.0  3        3.8       1
50  Sreekanth Krishnan  HR          Kochi     Manager           28000.0  1        3.9       1
51  Sanjay Devi         IT          Calicut   Senior Developer  64500.0  9        4.7       1
53  Kiran G             IT          Calicut   QA Engineer       47000.0  4        4.6       1
37  Maya Thomas         IT          Kannur    Lead              65000.0  8        4.6       1
54  Lakshmi G           Sales       Thrissur  Manager           26000.0  5        3.9       1
55  Anoop K             Sales       Kochi     Senior Executive  29000.0  1        3.6       1
56  Deepa Thomas        Sales       Kochi     Manager           25500.0  12       4.1       1
57  Manoj C             IT          Calicut   Senior Developer  59500.0  6        4.4       1
58  Ajay T              HR          Palakkad  Executive         30000.0  7        4.4       1
59  Joseph Kumar        Finance     Thrissur  Senior Analyst    38500.0  7        4.6       1
60  Sreeja Devi         Finance     Calicut   Senior Analyst    48000.0  11       4.3       1
61  Priya Nair          IT          Kochi     Developer         45000.0  5        4.7       1
62  Anoop M             IT          Calicut   Developer         43000.0  5        4.3       1
38  Sneha Devi          Finance     Calicut   Analyst           44500.0  12       3.9       1
35  Vishnu G            IT          Thrissur  QA Engineer       56500.0  8        3.6       1
2   Priya Nair          IT          Kochi     Developer         45000.0  5        4.7       1
20  Jishnu C            IT          Kochi     Lead              65000.0  11       4.9       1
4   Sneha Das           Sales       Thrissur  Executive         29000.0  2        3.9       1
5   Vijay S             IT          Kochi     Developer         47000.0  6        4.5       1
8   Arun Kumar          Sales       Calicut   Executive         28000.0  3        4.2       1
9   Divya R             HR          Thrissur  Executive         26000.0  1        3.5       1
11  Anoop M             IT          Calicut   Developer         43000.0  5        4.3       1
13  Rajan T             Finance     Calicut   Senior Analyst    41000.0  6        4.0       1
16  Sreeja V            HR          Calicut   Executive         25000.0  1        3.8       1
18  Lakshmi G           Sales       Thrissur  Executive         27000.0  2        3.6       1
19  Arun Kumar          Sales       Calicut   Executive         28000.0  3        4.2       1
22  Jishnu M            Sales       Palakkad  Senior Executive  25000.0  9        3.7       1
34  Bindu S             Sales       Kochi     Senior Executive  32500.0  9        3.6       1
23  Sreeja C            Sales       Thrissur  Manager           27000.0  4        4.8       1
24  Rahul Pillai        HR          Palakkad  Executive         36000.0  2        4.2       1
25  Rahul Devi          Sales       Kochi     Manager           26000.0  4        4.7       1
26  Jishnu Devi         HR          Thrissur  Recruiter         26000.0  10       4.4       1
28  Pradeep G           IT          Kannur    Lead              48000.0  3        3.8       1
29  Manoj M             Finance     Kochi     Manager           47500.0  2        4.5       1
31  Suresh Das          HR          Thrissur  Manager           29000.0  8        3.4       1
32  Vishnu Raj          Sales       Palakkad  Senior Executive  28000.0  3        4.0       1
33  Pradeep Kumar       HR          Calicut   Manager           33500.0  4        3.5       1
63  Jishnu Devi         HR          Thrissur  Recruiter         26000.0  10       4.4       1
Name: count, dtype: int64

In [759]:
df.size

504

## QS 6

In [760]:
df["Department"].unique()

array(['Sales', 'IT', 'HR', 'Finance'], dtype=object)

## QS 7

In [761]:
df["Department"].value_counts()

Department
Sales      19
IT         19
HR         16
Finance     9
Name: count, dtype: int64

## QS 8

In [762]:
df["City"].value_counts()

City
Calicut     18
Kochi       15
Thrissur    12
Palakkad     8
Kannur       4
Name: count, dtype: int64

## QS 9

In [763]:
df["Job Role"].unique()

array(['Executive', 'Developer', 'Manager', 'Analyst', 'Lead',
       'Senior Analyst', 'Senior Executive', 'Recruiter', 'QA Engineer',
       'Senior Developer'], dtype=object)

## QS 10

In [764]:
df[["Name","Department","Salary"]]

            Name Department   Salary
0     Arun Kumar      Sales  28000.0
1     Priya Nair         IT  45000.0
2    Rahul Menon         HR  38000.0
3      Sneha Das      Sales  29000.0
4        Vijay S         IT  47000.0
..           ...        ...      ...
58  Joseph Kumar    Finance  38500.0
59   Sreeja Devi    Finance  48000.0
60    Priya Nair         IT  45000.0
61       Anoop M         IT  43000.0
62   Jishnu Devi         HR  26000.0

[63 rows x 3 columns]

# SECTION B: DATA CLEANING

## QS 11

In [765]:
df

,ID,Name,Department,City,Job Role,Salary,Exp_Yrs,Rating
0,1,Arun Kumar,Sales,Calicut,Executive,28000.0,3,4.2
1,2,Priya Nair,IT,Kochi,Developer,45000.0,5,4.7
2,3,Rahul Menon,HR,Calicut,Manager,38000.0,7,NaN
3,4,Sneha Das,Sales,Thrissur,Executive,29000.0,2,3.9
4,5,Vijay S,IT,Kochi,Developer,47000.0,6,4.5
...,...,...,...,...,...,...,...,...
58,59,Joseph Kumar,Finance,Thrissur,Senior Analyst,38500.0,7,4.6
59,60,Sreeja Devi,Finance,Calicut,Senior Analyst,48000.0,11,4.3
60,61,Priya Nair,IT,Kochi,Developer,45000.0,5,4.7
61,62,Anoop M,IT,Calicut,Developer,43000.0,5,4.3
62,63,Jishnu Devi,HR,Thrissur,Recruiter,26000.0,10,4.4

In [766]:
df.isnull().sum()

ID            0
Name          5
Department    0
City          6
Job Role      0
Salary        1
Exp_Yrs       0
Rating        5
dtype: int64

## QS 12

In [767]:
df

,ID,Name,Department,City,Job Role,Salary,Exp_Yrs,Rating
0,1,Arun Kumar,Sales,Calicut,Executive,28000.0,3,4.2
1,2,Priya Nair,IT,Kochi,Developer,45000.0,5,4.7
2,3,Rahul Menon,HR,Calicut,Manager,38000.0,7,NaN
3,4,Sneha Das,Sales,Thrissur,Executive,29000.0,2,3.9
4,5,Vijay S,IT,Kochi,Developer,47000.0,6,4.5
...,...,...,...,...,...,...,...,...
58,59,Joseph Kumar,Finance,Thrissur,Senior Analyst,38500.0,7,4.6
59,60,Sreeja Devi,Finance,Calicut,Senior Analyst,48000.0,11,4.3
60,61,Priya Nair,IT,Kochi,Developer,45000.0,5,4.7
61,62,Anoop M,IT,Calicut,Developer,43000.0,5,4.3
62,63,Jishnu Devi,HR,Thrissur,Recruiter,26000.0,10,4.4

In [768]:
df.duplicated()

0     False
1     False
2     False
3     False
4     False
      ...
58    False
59    False
60    False
61    False
62    False
Length: 63, dtype: bool

In [769]:
df.duplicated().sum()

np.int64(0)

## QS 13

In [770]:
df.duplicated()

0     False
1     False
2     False
3     False
4     False
      ...
58    False
59    False
60    False
61    False
62    False
Length: 63, dtype: bool

In [771]:
df.duplicated().sum()

np.int64(0)

In [772]:
df.drop_duplicates()

,ID,Name,Department,City,Job Role,Salary,Exp_Yrs,Rating
0,1,Arun Kumar,Sales,Calicut,Executive,28000.0,3,4.2
1,2,Priya Nair,IT,Kochi,Developer,45000.0,5,4.7
2,3,Rahul Menon,HR,Calicut,Manager,38000.0,7,NaN
3,4,Sneha Das,Sales,Thrissur,Executive,29000.0,2,3.9
4,5,Vijay S,IT,Kochi,Developer,47000.0,6,4.5
...,...,...,...,...,...,...,...,...
58,59,Joseph Kumar,Finance,Thrissur,Senior Analyst,38500.0,7,4.6
59,60,Sreeja Devi,Finance,Calicut,Senior Analyst,48000.0,11,4.3
60,61,Priya Nair,IT,Kochi,Developer,45000.0,5,4.7
61,62,Anoop M,IT,Calicut,Developer,43000.0,5,4.3
62,63,Jishnu Devi,HR,Thrissur,Recruiter,26000.0,10,4.4

In [773]:
df.shape

(63, 8)

In [774]:
drop=df.drop_duplicates()

In [775]:
drop.duplicated().sum()

np.int64(0)

In [776]:
df.drop_duplicates(inplace=True)

In [777]:
df.shape

(63, 8)

## QS 14

In [778]:
df.columns

Index(['ID', 'Name', 'Department', 'City', 'Job Role', 'Salary', 'Exp_Yrs',
       'Rating'],
      dtype='object')

In [779]:
df=df.drop(columns=["ID"])

In [780]:
df

,Name,Department,City,Job Role,Salary,Exp_Yrs,Rating
0,Arun Kumar,Sales,Calicut,Executive,28000.0,3,4.2
1,Priya Nair,IT,Kochi,Developer,45000.0,5,4.7
2,Rahul Menon,HR,Calicut,Manager,38000.0,7,NaN
3,Sneha Das,Sales,Thrissur,Executive,29000.0,2,3.9
4,Vijay S,IT,Kochi,Developer,47000.0,6,4.5
...,...,...,...,...,...,...,...
58,Joseph Kumar,Finance,Thrissur,Senior Analyst,38500.0,7,4.6
59,Sreeja Devi,Finance,Calicut,Senior Analyst,48000.0,11,4.3
60,Priya Nair,IT,Kochi,Developer,45000.0,5,4.7
61,Anoop M,IT,Calicut,Developer,43000.0,5,4.3
62,Jishnu Devi,HR,Thrissur,Recruiter,26000.0,10,4.4

In [781]:
df.columns

Index(['Name', 'Department', 'City', 'Job Role', 'Salary', 'Exp_Yrs',
       'Rating'],
      dtype='object')

## QS 15

In [782]:
df.isnull()

     Name  Department   City  Job Role  Salary  Exp_Yrs  Rating
0   False       False  False     False   False    False   False
1   False       False  False     False   False    False   False
2   False       False  False     False   False    False    True
3   False       False  False     False   False    False   False
4   False       False  False     False   False    False   False
..    ...         ...    ...       ...     ...      ...     ...
58  False       False  False     False   False    False   False
59  False       False  False     False   False    False   False
60  False       False  False     False   False    False   False
61  False       False  False     False   False    False   False
62  False       False  False     False   False    False   False

[63 rows x 7 columns]

In [783]:
df.isnull().sum()

Name          5
Department    0
City          6
Job Role      0
Salary        1
Exp_Yrs       0
Rating        5
dtype: int64

In [784]:
print("Before:",df.shape)

df = df.dropna()

print("After:",df.shape)

Before: (63, 7)
After: (47, 7)

## QS 16

In [785]:
df

,Name,Department,City,Job Role,Salary,Exp_Yrs,Rating
0,Arun Kumar,Sales,Calicut,Executive,28000.0,3,4.2
1,Priya Nair,IT,Kochi,Developer,45000.0,5,4.7
3,Sneha Das,Sales,Thrissur,Executive,29000.0,2,3.9
4,Vijay S,IT,Kochi,Developer,47000.0,6,4.5
7,Arun Kumar,Sales,Calicut,Executive,28000.0,3,4.2
8,Divya R,HR,Thrissur,Executive,26000.0,1,3.5
10,Anoop M,IT,Calicut,Developer,43000.0,5,4.3
12,Rajan T,Finance,Calicut,Senior Analyst,41000.0,6,4.0
15,Sreeja V,HR,Calicut,Executive,25000.0,1,3.8
17,Lakshmi G,Sales,Thrissur,Executive,27000.0,2,3.6
18,Arun Kumar,Sales,Calicut,Executive,28000.0,3,4.2
19,Jishnu C,IT,Kochi,Lead,65000.0,11,4.9
21,Jishnu M,Sales,Palakkad,Senior Executive,25000.0,9,3.7
22,Sreeja C,Sales,Thrissur,Manager,27000.0,4,4.8
23,Rahul Pillai,HR,Palakkad,Executive,36000.0,2,4.2
24,Rahul Devi,Sales,Kochi,Manager,26000.0,4,4.7
25,Jishnu Devi,HR,Thrissur,Recruiter,26000.0,10,4.4
27,Pradeep G,IT,Kannur,Lead,48000.0,3,3.8
28,Manoj M,Finance,Kochi,Manager,47500.0,2,4.5
30,Suresh Das,HR,Thrissur,Manager,29000.0,8,3.4
31,Vishnu Raj,Sales,Palakkad,Senior Executive,28000.0,3,4.0
32,Pradeep Kumar,HR,Calicut,Manager,33500.0,4,3.5
33,Bindu S,Sales,Kochi,Senior Executive,32500.0,9,3.6
34,Vishnu G,IT,Thrissur,QA Engineer,56500.0,8,3.6
36,Maya Thomas,IT,Kannur,Lead,65000.0,8,4.6
37,Sneha Devi,Finance,Calicut,Analyst,44500.0,12,3.9
38,Naveen K,Finance,Kannur,Analyst,34000.0,8,4.6
41,Sneha Nair,HR,Palakkad,Manager,29000.0,1,4.8
42,Ajay Das,IT,Palakkad,Lead,58500.0,10,3.5
43,Jishnu Devi,HR,Thrissur,Executive,32000.0,7,3.6
44,Sajith Mathew,Sales,Palakkad,Executive,26000.0,9,3.7
45,Nimisha R,HR,Kannur,Recruiter,33500.0,10,4.9
46,Fathima K,Sales,Calicut,Executive,33500.0,3,3.8
49,Sreekanth Krishnan,HR,Kochi,Manager,28000.0,1,3.9
50,Sanjay Devi,IT,Calicut,Senior Developer,64500.0,9,4.7
51,Naveen C,IT,Calicut,Lead,63500.0,6,4.6
52,Kiran G,IT,Calicut,QA Engineer,47000.0,4,4.6
53,Lakshmi G,Sales,Thrissur,Manager,26000.0,5,3.9
54,Anoop K,Sales,Kochi,Senior Executive,29000.0,1,3.6
55,Deepa Thomas,Sales,Kochi,Manager,25500.0,12,4.1
56,Manoj C,IT,Calicut,Senior Developer,59500.0,6,4.4
57,Ajay T,HR,Palakkad,Executive,30000.0,7,4.4
58,Joseph Kumar,Finance,Thrissur,Senior Analyst,38500.0,7,4.6
59,Sreeja Devi,Finance,Calicut,Senior Analyst,48000.0,11,4.3
60,Priya Nair,IT,Kochi,Developer,45000.0,5,4.7
61,Anoop M,IT,Calicut,Developer,43000.0,5,4.3
62,Jishnu Devi,HR,Thrissur,Recruiter,26000.0,10,4.4

In [786]:
df["Salary"].isnull().sum()

np.int64(0)

In [787]:
df=df.dropna(subset=["Salary"])
print(df["Salary"].isnull().sum())

0

## QS 17

In [788]:
df = df.drop_duplicates()

In [789]:
df

,Name,Department,City,Job Role,Salary,Exp_Yrs,Rating
0,Arun Kumar,Sales,Calicut,Executive,28000.0,3,4.2
1,Priya Nair,IT,Kochi,Developer,45000.0,5,4.7
3,Sneha Das,Sales,Thrissur,Executive,29000.0,2,3.9
4,Vijay S,IT,Kochi,Developer,47000.0,6,4.5
8,Divya R,HR,Thrissur,Executive,26000.0,1,3.5
10,Anoop M,IT,Calicut,Developer,43000.0,5,4.3
12,Rajan T,Finance,Calicut,Senior Analyst,41000.0,6,4.0
15,Sreeja V,HR,Calicut,Executive,25000.0,1,3.8
17,Lakshmi G,Sales,Thrissur,Executive,27000.0,2,3.6
19,Jishnu C,IT,Kochi,Lead,65000.0,11,4.9
21,Jishnu M,Sales,Palakkad,Senior Executive,25000.0,9,3.7
22,Sreeja C,Sales,Thrissur,Manager,27000.0,4,4.8
23,Rahul Pillai,HR,Palakkad,Executive,36000.0,2,4.2
24,Rahul Devi,Sales,Kochi,Manager,26000.0,4,4.7
25,Jishnu Devi,HR,Thrissur,Recruiter,26000.0,10,4.4
27,Pradeep G,IT,Kannur,Lead,48000.0,3,3.8
28,Manoj M,Finance,Kochi,Manager,47500.0,2,4.5
30,Suresh Das,HR,Thrissur,Manager,29000.0,8,3.4
31,Vishnu Raj,Sales,Palakkad,Senior Executive,28000.0,3,4.0
32,Pradeep Kumar,HR,Calicut,Manager,33500.0,4,3.5
33,Bindu S,Sales,Kochi,Senior Executive,32500.0,9,3.6
34,Vishnu G,IT,Thrissur,QA Engineer,56500.0,8,3.6
36,Maya Thomas,IT,Kannur,Lead,65000.0,8,4.6
37,Sneha Devi,Finance,Calicut,Analyst,44500.0,12,3.9
38,Naveen K,Finance,Kannur,Analyst,34000.0,8,4.6
41,Sneha Nair,HR,Palakkad,Manager,29000.0,1,4.8
42,Ajay Das,IT,Palakkad,Lead,58500.0,10,3.5
43,Jishnu Devi,HR,Thrissur,Executive,32000.0,7,3.6
44,Sajith Mathew,Sales,Palakkad,Executive,26000.0,9,3.7
45,Nimisha R,HR,Kannur,Recruiter,33500.0,10,4.9
46,Fathima K,Sales,Calicut,Executive,33500.0,3,3.8
49,Sreekanth Krishnan,HR,Kochi,Manager,28000.0,1,3.9
50,Sanjay Devi,IT,Calicut,Senior Developer,64500.0,9,4.7
51,Naveen C,IT,Calicut,Lead,63500.0,6,4.6
52,Kiran G,IT,Calicut,QA Engineer,47000.0,4,4.6
53,Lakshmi G,Sales,Thrissur,Manager,26000.0,5,3.9
54,Anoop K,Sales,Kochi,Senior Executive,29000.0,1,3.6
55,Deepa Thomas,Sales,Kochi,Manager,25500.0,12,4.1
56,Manoj C,IT,Calicut,Senior Developer,59500.0,6,4.4
57,Ajay T,HR,Palakkad,Executive,30000.0,7,4.4
58,Joseph Kumar,Finance,Thrissur,Senior Analyst,38500.0,7,4.6
59,Sreeja Devi,Finance,Calicut,Senior Analyst,48000.0,11,4.3

In [790]:
it= df[df["Department"]== "IT"]
print(it[["Name", "Job Role"]])
print(it.shape[0])

           Name          Job Role
1    Priya Nair         Developer
4       Vijay S         Developer
10      Anoop M         Developer
19     Jishnu C              Lead
27    Pradeep G              Lead
34     Vishnu G       QA Engineer
36  Maya Thomas              Lead
42     Ajay Das              Lead
50  Sanjay Devi  Senior Developer
51     Naveen C              Lead
52      Kiran G       QA Engineer
56      Manoj C  Senior Developer
12

In [791]:
it

,Name,Department,City,Job Role,Salary,Exp_Yrs,Rating
1,Priya Nair,IT,Kochi,Developer,45000.0,5,4.7
4,Vijay S,IT,Kochi,Developer,47000.0,6,4.5
10,Anoop M,IT,Calicut,Developer,43000.0,5,4.3
19,Jishnu C,IT,Kochi,Lead,65000.0,11,4.9
27,Pradeep G,IT,Kannur,Lead,48000.0,3,3.8
34,Vishnu G,IT,Thrissur,QA Engineer,56500.0,8,3.6
36,Maya Thomas,IT,Kannur,Lead,65000.0,8,4.6
42,Ajay Das,IT,Palakkad,Lead,58500.0,10,3.5
50,Sanjay Devi,IT,Calicut,Senior Developer,64500.0,9,4.7
51,Naveen C,IT,Calicut,Lead,63500.0,6,4.6
52,Kiran G,IT,Calicut,QA Engineer,47000.0,4,4.6
56,Manoj C,IT,Calicut,Senior Developer,59500.0,6,4.4

## QS 18

In [792]:
df

,Name,Department,City,Job Role,Salary,Exp_Yrs,Rating
0,Arun Kumar,Sales,Calicut,Executive,28000.0,3,4.2
1,Priya Nair,IT,Kochi,Developer,45000.0,5,4.7
3,Sneha Das,Sales,Thrissur,Executive,29000.0,2,3.9
4,Vijay S,IT,Kochi,Developer,47000.0,6,4.5
8,Divya R,HR,Thrissur,Executive,26000.0,1,3.5
10,Anoop M,IT,Calicut,Developer,43000.0,5,4.3
12,Rajan T,Finance,Calicut,Senior Analyst,41000.0,6,4.0
15,Sreeja V,HR,Calicut,Executive,25000.0,1,3.8
17,Lakshmi G,Sales,Thrissur,Executive,27000.0,2,3.6
19,Jishnu C,IT,Kochi,Lead,65000.0,11,4.9
21,Jishnu M,Sales,Palakkad,Senior Executive,25000.0,9,3.7
22,Sreeja C,Sales,Thrissur,Manager,27000.0,4,4.8
23,Rahul Pillai,HR,Palakkad,Executive,36000.0,2,4.2
24,Rahul Devi,Sales,Kochi,Manager,26000.0,4,4.7
25,Jishnu Devi,HR,Thrissur,Recruiter,26000.0,10,4.4
27,Pradeep G,IT,Kannur,Lead,48000.0,3,3.8
28,Manoj M,Finance,Kochi,Manager,47500.0,2,4.5
30,Suresh Das,HR,Thrissur,Manager,29000.0,8,3.4
31,Vishnu Raj,Sales,Palakkad,Senior Executive,28000.0,3,4.0
32,Pradeep Kumar,HR,Calicut,Manager,33500.0,4,3.5
33,Bindu S,Sales,Kochi,Senior Executive,32500.0,9,3.6
34,Vishnu G,IT,Thrissur,QA Engineer,56500.0,8,3.6
36,Maya Thomas,IT,Kannur,Lead,65000.0,8,4.6
37,Sneha Devi,Finance,Calicut,Analyst,44500.0,12,3.9
38,Naveen K,Finance,Kannur,Analyst,34000.0,8,4.6
41,Sneha Nair,HR,Palakkad,Manager,29000.0,1,4.8
42,Ajay Das,IT,Palakkad,Lead,58500.0,10,3.5
43,Jishnu Devi,HR,Thrissur,Executive,32000.0,7,3.6
44,Sajith Mathew,Sales,Palakkad,Executive,26000.0,9,3.7
45,Nimisha R,HR,Kannur,Recruiter,33500.0,10,4.9
46,Fathima K,Sales,Calicut,Executive,33500.0,3,3.8
49,Sreekanth Krishnan,HR,Kochi,Manager,28000.0,1,3.9
50,Sanjay Devi,IT,Calicut,Senior Developer,64500.0,9,4.7
51,Naveen C,IT,Calicut,Lead,63500.0,6,4.6
52,Kiran G,IT,Calicut,QA Engineer,47000.0,4,4.6
53,Lakshmi G,Sales,Thrissur,Manager,26000.0,5,3.9
54,Anoop K,Sales,Kochi,Senior Executive,29000.0,1,3.6
55,Deepa Thomas,Sales,Kochi,Manager,25500.0,12,4.1
56,Manoj C,IT,Calicut,Senior Developer,59500.0,6,4.4
57,Ajay T,HR,Palakkad,Executive,30000.0,7,4.4
58,Joseph Kumar,Finance,Thrissur,Senior Analyst,38500.0,7,4.6
59,Sreeja Devi,Finance,Calicut,Senior Analyst,48000.0,11,4.3

In [793]:
import pandas as pd

df=pd.read_csv(r"C:\Users\SANITHA\Documents\data analytics\review\files\employee_data.csv")

In [794]:
df.isnull().sum()

ID            0
Name          5
Department    0
City          6
Job Role      0
Salary        1
Exp_Yrs       0
Rating        5
dtype: int64

In [795]:
missing=df.isnull().sum
print(df.columns[df.isnull().sum() > 1])

Index(['Name', 'City', 'Rating'], dtype='object')

## QS 19

In [796]:
df

,ID,Name,Department,City,Job Role,Salary,Exp_Yrs,Rating
0,1,Arun Kumar,Sales,Calicut,Executive,28000.0,3,4.2
1,2,Priya Nair,IT,Kochi,Developer,45000.0,5,4.7
2,3,Rahul Menon,HR,Calicut,Manager,38000.0,7,NaN
3,4,Sneha Das,Sales,Thrissur,Executive,29000.0,2,3.9
4,5,Vijay S,IT,Kochi,Developer,47000.0,6,4.5
...,...,...,...,...,...,...,...,...
58,59,Joseph Kumar,Finance,Thrissur,Senior Analyst,38500.0,7,4.6
59,60,Sreeja Devi,Finance,Calicut,Senior Analyst,48000.0,11,4.3
60,61,Priya Nair,IT,Kochi,Developer,45000.0,5,4.7
61,62,Anoop M,IT,Calicut,Developer,43000.0,5,4.3
62,63,Jishnu Devi,HR,Thrissur,Recruiter,26000.0,10,4.4

In [797]:
# remove duplicates rows

df.drop_duplicates
print(df.shape)

# drop id columns

df.drop("ID",axis=1, inplace=True)
print(df.shape)

# drop rows with null values

df.dropna(inplace=True)
print(df.shape)

(63, 8)
(63, 7)
(47, 7)

## QS 20

In [798]:
df=df.drop_duplicates()

In [799]:
df

,Name,Department,City,Job Role,Salary,Exp_Yrs,Rating
0,Arun Kumar,Sales,Calicut,Executive,28000.0,3,4.2
1,Priya Nair,IT,Kochi,Developer,45000.0,5,4.7
3,Sneha Das,Sales,Thrissur,Executive,29000.0,2,3.9
4,Vijay S,IT,Kochi,Developer,47000.0,6,4.5
8,Divya R,HR,Thrissur,Executive,26000.0,1,3.5
10,Anoop M,IT,Calicut,Developer,43000.0,5,4.3
12,Rajan T,Finance,Calicut,Senior Analyst,41000.0,6,4.0
15,Sreeja V,HR,Calicut,Executive,25000.0,1,3.8
17,Lakshmi G,Sales,Thrissur,Executive,27000.0,2,3.6
19,Jishnu C,IT,Kochi,Lead,65000.0,11,4.9
21,Jishnu M,Sales,Palakkad,Senior Executive,25000.0,9,3.7
22,Sreeja C,Sales,Thrissur,Manager,27000.0,4,4.8
23,Rahul Pillai,HR,Palakkad,Executive,36000.0,2,4.2
24,Rahul Devi,Sales,Kochi,Manager,26000.0,4,4.7
25,Jishnu Devi,HR,Thrissur,Recruiter,26000.0,10,4.4
27,Pradeep G,IT,Kannur,Lead,48000.0,3,3.8
28,Manoj M,Finance,Kochi,Manager,47500.0,2,4.5
30,Suresh Das,HR,Thrissur,Manager,29000.0,8,3.4
31,Vishnu Raj,Sales,Palakkad,Senior Executive,28000.0,3,4.0
32,Pradeep Kumar,HR,Calicut,Manager,33500.0,4,3.5
33,Bindu S,Sales,Kochi,Senior Executive,32500.0,9,3.6
34,Vishnu G,IT,Thrissur,QA Engineer,56500.0,8,3.6
36,Maya Thomas,IT,Kannur,Lead,65000.0,8,4.6
37,Sneha Devi,Finance,Calicut,Analyst,44500.0,12,3.9
38,Naveen K,Finance,Kannur,Analyst,34000.0,8,4.6
41,Sneha Nair,HR,Palakkad,Manager,29000.0,1,4.8
42,Ajay Das,IT,Palakkad,Lead,58500.0,10,3.5
43,Jishnu Devi,HR,Thrissur,Executive,32000.0,7,3.6
44,Sajith Mathew,Sales,Palakkad,Executive,26000.0,9,3.7
45,Nimisha R,HR,Kannur,Recruiter,33500.0,10,4.9
46,Fathima K,Sales,Calicut,Executive,33500.0,3,3.8
49,Sreekanth Krishnan,HR,Kochi,Manager,28000.0,1,3.9
50,Sanjay Devi,IT,Calicut,Senior Developer,64500.0,9,4.7
51,Naveen C,IT,Calicut,Lead,63500.0,6,4.6
52,Kiran G,IT,Calicut,QA Engineer,47000.0,4,4.6
53,Lakshmi G,Sales,Thrissur,Manager,26000.0,5,3.9
54,Anoop K,Sales,Kochi,Senior Executive,29000.0,1,3.6
55,Deepa Thomas,Sales,Kochi,Manager,25500.0,12,4.1
56,Manoj C,IT,Calicut,Senior Developer,59500.0,6,4.4
57,Ajay T,HR,Palakkad,Executive,30000.0,7,4.4
58,Joseph Kumar,Finance,Thrissur,Senior Analyst,38500.0,7,4.6
59,Sreeja Devi,Finance,Calicut,Senior Analyst,48000.0,11,4.3

In [801]:
df.groupby("Department").size()

Department
Finance     6
HR         11
IT         12
Sales      13
dtype: int64

In [802]:
df["City"].unique()

array(['Calicut', 'Kochi', 'Thrissur', 'Palakkad', 'Kannur'], dtype=object)

In [803]:
df["Exp_Yrs"].mean()

np.float64(5.833333333333333)