In [ ]:
import pandas as pd

In [ ]:
#q1
df=pd.read_csv("/content/drive/MyDrive/Data analytics/Review/netflix_titles.csv")

In [ ]:
#q2
df.head(10)

,show_id,type,title,director,cast,country,date_added,release_year,rating,duration,listed_in,description
0,s1,Movie,Dick Johnson Is Dead,Kirsten Johnson,NaN,United States,"September 25, 2021",2020,PG-13,90 min,Documentaries,"As her father nears the end of his life, filmm..."
1,s2,TV Show,Blood & Water,NaN,"Ama Qamata, Khosi Ngema, Gail Mabalane, Thaban...",South Africa,"September 24, 2021",2021,TV-MA,2 Seasons,"International TV Shows, TV Dramas, TV Mysteries","After crossing paths at a party, a Cape Town t..."
2,s3,TV Show,Ganglands,Julien Leclercq,"Sami Bouajila, Tracy Gotoas, Samuel Jouy, Nabi...",NaN,"September 24, 2021",2021,TV-MA,1 Season,"Crime TV Shows, International TV Shows, TV Act...",To protect his family from a powerful drug lor...
3,s4,TV Show,Jailbirds New Orleans,NaN,NaN,NaN,"September 24, 2021",2021,TV-MA,1 Season,"Docuseries, Reality TV","Feuds, flirtations and toilet talk go down amo..."
4,s5,TV Show,Kota Factory,NaN,"Mayur More, Jitendra Kumar, Ranjan Raj, Alam K...",India,"September 24, 2021",2021,TV-MA,2 Seasons,"International TV Shows, Romantic TV Shows, TV ...",In a city of coaching centers known to train I...
5,s6,TV Show,Midnight Mass,Mike Flanagan,"Kate Siegel, Zach Gilford, Hamish Linklater, H...",NaN,"September 24, 2021",2021,TV-MA,1 Season,"TV Dramas, TV Horror, TV Mysteries",The arrival of a charismatic young priest brin...
6,s7,Movie,My Little Pony: A New Generation,"Robert Cullen, José Luis Ucha","Vanessa Hudgens, Kimiko Glenn, James Marsden, ...",NaN,"September 24, 2021",2021,PG,91 min,Children & Family Movies,Equestria's divided. But a bright-eyed hero be...
7,s8,Movie,Sankofa,Haile Gerima,"Kofi Ghanaba, Oyafunmike Ogunlano, Alexandra D...","United States, Ghana, Burkina Faso, United Kin...","September 24, 2021",1993,TV-MA,125 min,"Dramas, Independent Movies, International Movies","On a photo shoot in Ghana, an American model s..."
8,s9,TV Show,The Great British Baking Show,Andy Devonshire,"Mel Giedroyc, Sue Perkins, Mary Berry, Paul Ho...",United Kingdom,"September 24, 2021",2021,TV-14,9 Seasons,"British TV Shows, Reality TV",A talented batch of amateur bakers face off in...
9,s10,Movie,The Starling,Theodore Melfi,"Melissa McCarthy, Chris O'Dowd, Kevin Kline, T...",United States,"September 24, 2021",2021,PG-13,104 min,"Comedies, Dramas",A woman adjusting to life after a loss contend...

In [ ]:
#Q3
df.shape

(8807, 12)

In [ ]:
#Q4
df.columns

Index(['show_id', 'type', 'title', 'director', 'cast', 'country', 'date_added',
       'release_year', 'rating', 'duration', 'listed_in', 'description'],
      dtype='object')

In [ ]:
df.dtypes

show_id         object
type            object
title           object
director        object
cast            object
country         object
date_added      object
release_year     int64
rating          object
duration        object
listed_in       object
description     object
dtype: object

In [ ]:
#Q5
df.isnull().sum()

show_id            0
type               0
title              0
director        2634
cast             825
country          831
date_added        10
release_year       0
rating             4
duration           3
listed_in          0
description        0
dtype: int64

In [ ]:
#Q6
df["rating"].nunique()

17

In [ ]:
#Q7
df[df['type']=="Movie"]

,show_id,type,title,director,cast,country,date_added,release_year,rating,duration,listed_in,description
0,s1,Movie,Dick Johnson Is Dead,Kirsten Johnson,NaN,United States,"September 25, 2021",2020,PG-13,90 min,Documentaries,"As her father nears the end of his life, filmm..."
6,s7,Movie,My Little Pony: A New Generation,"Robert Cullen, José Luis Ucha","Vanessa Hudgens, Kimiko Glenn, James Marsden, ...",NaN,"September 24, 2021",2021,PG,91 min,Children & Family Movies,Equestria's divided. But a bright-eyed hero be...
7,s8,Movie,Sankofa,Haile Gerima,"Kofi Ghanaba, Oyafunmike Ogunlano, Alexandra D...","United States, Ghana, Burkina Faso, United Kin...","September 24, 2021",1993,TV-MA,125 min,"Dramas, Independent Movies, International Movies","On a photo shoot in Ghana, an American model s..."
9,s10,Movie,The Starling,Theodore Melfi,"Melissa McCarthy, Chris O'Dowd, Kevin Kline, T...",United States,"September 24, 2021",2021,PG-13,104 min,"Comedies, Dramas",A woman adjusting to life after a loss contend...
12,s13,Movie,Je Suis Karl,Christian Schwochow,"Luna Wedler, Jannis Niewöhner, Milan Peschel, ...","Germany, Czech Republic","September 23, 2021",2021,TV-MA,127 min,"Dramas, International Movies",After most of her family is murdered in a terr...
...,...,...,...,...,...,...,...,...,...,...,...,...
8801,s8802,Movie,Zinzana,Majid Al Ansari,"Ali Suliman, Saleh Bakri, Yasa, Ali Al-Jabri, ...","United Arab Emirates, Jordan","March 9, 2016",2015,TV-MA,96 min,"Dramas, International Movies, Thrillers",Recovering alcoholic Talal wakes up inside a s...
8802,s8803,Movie,Zodiac,David Fincher,"Mark Ruffalo, Jake Gyllenhaal, Robert Downey J...",United States,"November 20, 2019",2007,R,158 min,"Cult Movies, Dramas, Thrillers","A political cartoonist, a crime reporter and a..."
8804,s8805,Movie,Zombieland,Ruben Fleischer,"Jesse Eisenberg, Woody Harrelson, Emma Stone, ...",United States,"November 1, 2019",2009,R,88 min,"Comedies, Horror Movies",Looking to survive in a world taken over by zo...
8805,s8806,Movie,Zoom,Peter Hewitt,"Tim Allen, Courteney Cox, Chevy Chase, Kate Ma...",United States,"January 11, 2020",2006,PG,88 min,"Children & Family Movies, Comedies","Dragged from civilian life, a former superhero..."
8806,s8807,Movie,Zubaan,Mozez Singh,"Vicky Kaushal, Sarah-Jane Dias, Raaghav Chanan...",India,"March 2, 2019",2015,TV-14,111 min,"Dramas, International Movies, Music & Musicals",A scrappy but poor boy worms his way into a ty...

In [ ]:
#Q8
df[df['country']=="India"]

,show_id,type,title,director,cast,country,date_added,release_year,rating,duration,listed_in,description
4,s5,TV Show,Kota Factory,NaN,"Mayur More, Jitendra Kumar, Ranjan Raj, Alam K...",India,"September 24, 2021",2021,TV-MA,2 Seasons,"International TV Shows, Romantic TV Shows, TV ...",In a city of coaching centers known to train I...
24,s25,Movie,Jeans,S. Shankar,"Prashanth, Aishwarya Rai Bachchan, Sri Lakshmi...",India,"September 21, 2021",1998,TV-14,166 min,"Comedies, International Movies, Romantic Movies",When the father of the man she loves insists t...
39,s40,TV Show,Chhota Bheem,NaN,"Vatsal Dubey, Julie Tejwani, Rupa Bhimani, Jig...",India,"September 16, 2021",2021,TV-Y7,3 Seasons,Kids' TV,"A brave, energetic little boy with superhuman ..."
50,s51,TV Show,Dharmakshetra,NaN,"Kashmira Irani, Chandan Anand, Dinesh Mehta, A...",India,"September 15, 2021",2014,TV-PG,1 Season,"International TV Shows, TV Dramas, TV Sci-Fi &...","After the ancient Great War, the god Chitragup..."
66,s67,TV Show,Raja Rasoi Aur Anya Kahaniyan,NaN,NaN,India,"September 15, 2021",2014,TV-G,1 Season,"Docuseries, International TV Shows",Explore the history and flavors of regional In...
...,...,...,...,...,...,...,...,...,...,...,...,...
8773,s8774,Movie,Yanda Kartavya Aahe,Kedar Shinde,"Ankush Choudhary, Smita Shewale, Mohan Joshi, ...",India,"January 1, 2018",2006,TV-PG,151 min,"Comedies, Dramas, International Movies",Thanks to an arranged marriage that was design...
8775,s8776,TV Show,Yeh Meri Family,NaN,"Vishesh Bansal, Mona Singh, Akarsh Khurana, Ah...",India,"August 31, 2018",2018,TV-PG,1 Season,"International TV Shows, TV Comedies","In the summer of 1998, middle child Harshu bal..."
8798,s8799,Movie,Zed Plus,Chandra Prakash Dwivedi,"Adil Hussain, Mona Singh, K.K. Raina, Sanjay M...",India,"December 31, 2019",2014,TV-MA,131 min,"Comedies, Dramas, International Movies",A philandering small-town mechanic's political...
8799,s8800,Movie,Zenda,Avadhoot Gupte,"Santosh Juvekar, Siddharth Chandekar, Sachit P...",India,"February 15, 2018",2009,TV-14,120 min,"Dramas, International Movies",A change in the leadership of a political part...
8806,s8807,Movie,Zubaan,Mozez Singh,"Vicky Kaushal, Sarah-Jane Dias, Raaghav Chanan...",India,"March 2, 2019",2015,TV-14,111 min,"Dramas, International Movies, Music & Musicals",A scrappy but poor boy worms his way into a ty...

In [ ]:
#Q9
df[df['release_year']>2015]

,show_id,type,title,director,cast,country,date_added,release_year,rating,duration,listed_in,description
0,s1,Movie,Dick Johnson Is Dead,Kirsten Johnson,NaN,United States,"September 25, 2021",2020,PG-13,90 min,Documentaries,"As her father nears the end of his life, filmm..."
1,s2,TV Show,Blood & Water,NaN,"Ama Qamata, Khosi Ngema, Gail Mabalane, Thaban...",South Africa,"September 24, 2021",2021,TV-MA,2 Seasons,"International TV Shows, TV Dramas, TV Mysteries","After crossing paths at a party, a Cape Town t..."
2,s3,TV Show,Ganglands,Julien Leclercq,"Sami Bouajila, Tracy Gotoas, Samuel Jouy, Nabi...",NaN,"September 24, 2021",2021,TV-MA,1 Season,"Crime TV Shows, International TV Shows, TV Act...",To protect his family from a powerful drug lor...
3,s4,TV Show,Jailbirds New Orleans,NaN,NaN,NaN,"September 24, 2021",2021,TV-MA,1 Season,"Docuseries, Reality TV","Feuds, flirtations and toilet talk go down amo..."
4,s5,TV Show,Kota Factory,NaN,"Mayur More, Jitendra Kumar, Ranjan Raj, Alam K...",India,"September 24, 2021",2021,TV-MA,2 Seasons,"International TV Shows, Romantic TV Shows, TV ...",In a city of coaching centers known to train I...
...,...,...,...,...,...,...,...,...,...,...,...,...
8787,s8788,Movie,You Can’t Fight Christmas,Kenny Young,"Brely Evans, Andra Fuller, Persia White, Porsc...",United States,"December 19, 2017",2017,TV-PG,85 min,"Comedies, Romantic Movies",After stepping in to revitalize his family's h...
8794,s8795,Movie,اشتباك,Mohamed Diab,"Nelly Karim, Hany Adel, Tarek Abdel Aziz, Ahme...","Egypt, France","October 11, 2018",2016,TV-14,98 min,"Dramas, Independent Movies, International Movies",Amid the tumult following Egyptian President M...
8796,s8797,TV Show,Yunus Emre,NaN,"Gökhan Atalay, Payidar Tüfekçioglu, Baran Akbu...",Turkey,"January 17, 2017",2016,TV-PG,2 Seasons,"International TV Shows, TV Dramas","During the Mongol invasions, Yunus Emre leaves..."
8797,s8798,TV Show,Zak Storm,NaN,"Michael Johnston, Jessica Gee-George, Christin...","United States, France, South Korea, Indonesia","September 13, 2018",2016,TV-Y7,3 Seasons,Kids' TV,Teen surfer Zak Storm is mysteriously transpor...
8803,s8804,TV Show,Zombie Dumb,NaN,NaN,NaN,"July 1, 2019",2018,TV-Y7,2 Seasons,"Kids' TV, Korean TV Shows, TV Comedies","While living alone in a spooky town, a young g..."

In [ ]:
#Q10
df[df['title'].str.contains("Love")]

,show_id,type,title,director,cast,country,date_added,release_year,rating,duration,listed_in,description
25,s26,TV Show,Love on the Spectrum,NaN,Brooke Satchwell,Australia,"September 21, 2021",2021,TV-14,2 Seasons,"Docuseries, International TV Shows, Reality TV",Finding love can be hard for anyone. For young...
158,s159,Movie,Love Don't Cost a Thing,Troy Byer,"Nick Cannon, Christina Milian, Kenan Thompson,...",United States,"September 1, 2021",2003,PG-13,101 min,"Comedies, Romantic Movies",A nerdy teen tries to make himself cool by ass...
159,s160,Movie,Love in a Puff,Pang Ho-cheung,"Miriam Chin Wah Yeung, Shawn Yue, Singh Hartih...",Hong Kong,"September 1, 2021",2010,TV-MA,103 min,"Comedies, Dramas, International Movies",When the Hong Kong government enacts a ban on ...
206,s207,Movie,"LSD: Love, Sex Aur Dhokha",Dibakar Banerjee,"Nushrat Bharucha, Anshuman Jha, Neha Chauhan, ...",India,"August 27, 2021",2010,TV-MA,112 min,"Dramas, Independent Movies, International Movies",This provocative drama examines how the voyeur...
227,s228,Movie,Really Love,Angel Kristi Williams,"Kofi Siriboe, Yootha Wong-Loi-Sing, Michael Ea...",United States,"August 25, 2021",2020,TV-MA,95 min,"Dramas, Independent Movies, Romantic Movies",A rising Black painter tries to break into a c...
...,...,...,...,...,...,...,...,...,...,...,...,...
8567,s8568,TV Show,The Year of Happiness and Love,NaN,"Amber Kuo, James Wen, Weber Yang, Sonia Sui, N...",Taiwan,"September 1, 2016",2009,TV-PG,1 Season,"International TV Shows, Romantic TV Shows, TV ...",Jiang Chen-bo is a loser without prospects for...
8575,s8576,TV Show,This Is My Love,NaN,"Jin-mo Joo, Sa-rang Kim, Junior, Ja-in Lee, Su...",South Korea,"May 22, 2017",2015,TV-14,1 Season,"International TV Shows, Korean TV Shows, Roman...",A renowned actor who is still pining over the ...
8649,s8650,Movie,Two Lovers and a Bear,Kim Nguyen,"Dane DeHaan, Tatiana Maslany, Gordon Pinsent, ...",Canada,"May 2, 2017",2016,R,95 min,"Dramas, Independent Movies, Romantic Movies",A troubled couple living near the North Pole b...
8721,s8722,TV Show,What Is Love?,NaN,"Chris Wu, Jade Chou, Duncan Lai, King Chin, Ki...",Taiwan,"January 1, 2017",2012,TV-14,1 Season,"International TV Shows, Romantic TV Shows, TV ...",A 32-year-old romantic looking for a long-term...
8725,s8726,Movie,What's Up With Love?,"Rudy Soedjarwo, Riri Riza","Dian Sastrowardoyo, Nicholas Saputra, Ladya Ch...",Indonesia,"December 8, 2018",2002,R,110 min,"Dramas, International Movies, Romantic Movies",A popular high school girl strains her relatio...

In [ ]:
#Q11
df[df['duration'].str.contains("min",na=False)]

,show_id,type,title,director,cast,country,date_added,release_year,rating,duration,listed_in,description
0,s1,Movie,Dick Johnson Is Dead,Kirsten Johnson,NaN,United States,"September 25, 2021",2020,PG-13,90 min,Documentaries,"As her father nears the end of his life, filmm..."
6,s7,Movie,My Little Pony: A New Generation,"Robert Cullen, José Luis Ucha","Vanessa Hudgens, Kimiko Glenn, James Marsden, ...",NaN,"September 24, 2021",2021,PG,91 min,Children & Family Movies,Equestria's divided. But a bright-eyed hero be...
7,s8,Movie,Sankofa,Haile Gerima,"Kofi Ghanaba, Oyafunmike Ogunlano, Alexandra D...","United States, Ghana, Burkina Faso, United Kin...","September 24, 2021",1993,TV-MA,125 min,"Dramas, Independent Movies, International Movies","On a photo shoot in Ghana, an American model s..."
9,s10,Movie,The Starling,Theodore Melfi,"Melissa McCarthy, Chris O'Dowd, Kevin Kline, T...",United States,"September 24, 2021",2021,PG-13,104 min,"Comedies, Dramas",A woman adjusting to life after a loss contend...
12,s13,Movie,Je Suis Karl,Christian Schwochow,"Luna Wedler, Jannis Niewöhner, Milan Peschel, ...","Germany, Czech Republic","September 23, 2021",2021,TV-MA,127 min,"Dramas, International Movies",After most of her family is murdered in a terr...
...,...,...,...,...,...,...,...,...,...,...,...,...
8801,s8802,Movie,Zinzana,Majid Al Ansari,"Ali Suliman, Saleh Bakri, Yasa, Ali Al-Jabri, ...","United Arab Emirates, Jordan","March 9, 2016",2015,TV-MA,96 min,"Dramas, International Movies, Thrillers",Recovering alcoholic Talal wakes up inside a s...
8802,s8803,Movie,Zodiac,David Fincher,"Mark Ruffalo, Jake Gyllenhaal, Robert Downey J...",United States,"November 20, 2019",2007,R,158 min,"Cult Movies, Dramas, Thrillers","A political cartoonist, a crime reporter and a..."
8804,s8805,Movie,Zombieland,Ruben Fleischer,"Jesse Eisenberg, Woody Harrelson, Emma Stone, ...",United States,"November 1, 2019",2009,R,88 min,"Comedies, Horror Movies",Looking to survive in a world taken over by zo...
8805,s8806,Movie,Zoom,Peter Hewitt,"Tim Allen, Courteney Cox, Chevy Chase, Kate Ma...",United States,"January 11, 2020",2006,PG,88 min,"Children & Family Movies, Comedies","Dragged from civilian life, a former superhero..."
8806,s8807,Movie,Zubaan,Mozez Singh,"Vicky Kaushal, Sarah-Jane Dias, Raaghav Chanan...",India,"March 2, 2019",2015,TV-14,111 min,"Dramas, International Movies, Music & Musicals",A scrappy but poor boy worms his way into a ty...

In [ ]:
#Q12
df.dropna(subset=["director"])

,show_id,type,title,director,cast,country,date_added,release_year,rating,duration,listed_in,description
0,s1,Movie,Dick Johnson Is Dead,Kirsten Johnson,NaN,United States,"September 25, 2021",2020,PG-13,90 min,Documentaries,"As her father nears the end of his life, filmm..."
2,s3,TV Show,Ganglands,Julien Leclercq,"Sami Bouajila, Tracy Gotoas, Samuel Jouy, Nabi...",NaN,"September 24, 2021",2021,TV-MA,1 Season,"Crime TV Shows, International TV Shows, TV Act...",To protect his family from a powerful drug lor...
5,s6,TV Show,Midnight Mass,Mike Flanagan,"Kate Siegel, Zach Gilford, Hamish Linklater, H...",NaN,"September 24, 2021",2021,TV-MA,1 Season,"TV Dramas, TV Horror, TV Mysteries",The arrival of a charismatic young priest brin...
6,s7,Movie,My Little Pony: A New Generation,"Robert Cullen, José Luis Ucha","Vanessa Hudgens, Kimiko Glenn, James Marsden, ...",NaN,"September 24, 2021",2021,PG,91 min,Children & Family Movies,Equestria's divided. But a bright-eyed hero be...
7,s8,Movie,Sankofa,Haile Gerima,"Kofi Ghanaba, Oyafunmike Ogunlano, Alexandra D...","United States, Ghana, Burkina Faso, United Kin...","September 24, 2021",1993,TV-MA,125 min,"Dramas, Independent Movies, International Movies","On a photo shoot in Ghana, an American model s..."
...,...,...,...,...,...,...,...,...,...,...,...,...
8801,s8802,Movie,Zinzana,Majid Al Ansari,"Ali Suliman, Saleh Bakri, Yasa, Ali Al-Jabri, ...","United Arab Emirates, Jordan","March 9, 2016",2015,TV-MA,96 min,"Dramas, International Movies, Thrillers",Recovering alcoholic Talal wakes up inside a s...
8802,s8803,Movie,Zodiac,David Fincher,"Mark Ruffalo, Jake Gyllenhaal, Robert Downey J...",United States,"November 20, 2019",2007,R,158 min,"Cult Movies, Dramas, Thrillers","A political cartoonist, a crime reporter and a..."
8804,s8805,Movie,Zombieland,Ruben Fleischer,"Jesse Eisenberg, Woody Harrelson, Emma Stone, ...",United States,"November 1, 2019",2009,R,88 min,"Comedies, Horror Movies",Looking to survive in a world taken over by zo...
8805,s8806,Movie,Zoom,Peter Hewitt,"Tim Allen, Courteney Cox, Chevy Chase, Kate Ma...",United States,"January 11, 2020",2006,PG,88 min,"Children & Family Movies, Comedies","Dragged from civilian life, a former superhero..."
8806,s8807,Movie,Zubaan,Mozez Singh,"Vicky Kaushal, Sarah-Jane Dias, Raaghav Chanan...",India,"March 2, 2019",2015,TV-14,111 min,"Dramas, International Movies, Music & Musicals",A scrappy but poor boy worms his way into a ty...

In [ ]:
#Q13
df["country"].fillna("unknown",inplace=True)

/tmp/ipykernel_12818/2506534301.py:2: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df["country"].fillna("unknown",inplace=True)

In [ ]:
df

,show_id,type,title,director,cast,country,date_added,release_year,rating,duration,listed_in,description
0,s1,Movie,Dick Johnson Is Dead,Kirsten Johnson,NaN,United States,"September 25, 2021",2020,PG-13,90 min,Documentaries,"As her father nears the end of his life, filmm..."
1,s2,TV Show,Blood & Water,NaN,"Ama Qamata, Khosi Ngema, Gail Mabalane, Thaban...",South Africa,"September 24, 2021",2021,TV-MA,2 Seasons,"International TV Shows, TV Dramas, TV Mysteries","After crossing paths at a party, a Cape Town t..."
2,s3,TV Show,Ganglands,Julien Leclercq,"Sami Bouajila, Tracy Gotoas, Samuel Jouy, Nabi...",unknown,"September 24, 2021",2021,TV-MA,1 Season,"Crime TV Shows, International TV Shows, TV Act...",To protect his family from a powerful drug lor...
3,s4,TV Show,Jailbirds New Orleans,NaN,NaN,unknown,"September 24, 2021",2021,TV-MA,1 Season,"Docuseries, Reality TV","Feuds, flirtations and toilet talk go down amo..."
4,s5,TV Show,Kota Factory,NaN,"Mayur More, Jitendra Kumar, Ranjan Raj, Alam K...",India,"September 24, 2021",2021,TV-MA,2 Seasons,"International TV Shows, Romantic TV Shows, TV ...",In a city of coaching centers known to train I...
...,...,...,...,...,...,...,...,...,...,...,...,...
8802,s8803,Movie,Zodiac,David Fincher,"Mark Ruffalo, Jake Gyllenhaal, Robert Downey J...",United States,"November 20, 2019",2007,R,158 min,"Cult Movies, Dramas, Thrillers","A political cartoonist, a crime reporter and a..."
8803,s8804,TV Show,Zombie Dumb,NaN,NaN,unknown,"July 1, 2019",2018,TV-Y7,2 Seasons,"Kids' TV, Korean TV Shows, TV Comedies","While living alone in a spooky town, a young g..."
8804,s8805,Movie,Zombieland,Ruben Fleischer,"Jesse Eisenberg, Woody Harrelson, Emma Stone, ...",United States,"November 1, 2019",2009,R,88 min,"Comedies, Horror Movies",Looking to survive in a world taken over by zo...
8805,s8806,Movie,Zoom,Peter Hewitt,"Tim Allen, Courteney Cox, Chevy Chase, Kate Ma...",United States,"January 11, 2020",2006,PG,88 min,"Children & Family Movies, Comedies","Dragged from civilian life, a former superhero..."
8806,s8807,Movie,Zubaan,Mozez Singh,"Vicky Kaushal, Sarah-Jane Dias, Raaghav Chanan...",India,"March 2, 2019",2015,TV-14,111 min,"Dramas, International Movies, Music & Musicals",A scrappy but poor boy worms his way into a ty...

In [ ]:
#Q14
df["cast"].isnull().sum()

np.int64(825)

In [ ]:
#Q15
df["rating"].fillna("not rated")

0       PG-13
1       TV-MA
2       TV-MA
3       TV-MA
4       TV-MA
        ...
8802        R
8803    TV-Y7
8804        R
8805       PG
8806    TV-14
Name: rating, Length: 8807, dtype: object

In [ ]:
#Q16
df['date_added']=pd.to_datetime(df["date_added"],format="mixed")

In [ ]:
#Q17
df["year_added"]=df['date_added'].dt.year

In [ ]:
df['date_added'].head()

0   2021-09-25
1   2021-09-24
2   2021-09-24
3   2021-09-24
4   2021-09-24
Name: date_added, dtype: datetime64[ns]

In [ ]:
#Q18
df["month_name"]=df['date_added'].dt.month_name()

In [ ]:
#Q19
df[df['date_added'].dt.year==2020].shape[0]

1879

In [ ]:
df["year_added"]

0       2021.0
1       2021.0
2       2021.0
3       2021.0
4       2021.0
         ...
8802    2019.0
8803    2019.0
8804    2019.0
8805    2020.0
8806    2019.0
Name: year_added, Length: 8807, dtype: float64

In [ ]:
#Q20
df["date_added"].dt.month_name().value_counts().max()

827

In [ ]:
#Q21
df["release_year"].value_counts()

release_year
2018    1147
2017    1032
2019    1030
2020     953
2016     902
        ...
1961       1
1925       1
1959       1
1966       1
1947       1
Name: count, Length: 74, dtype: int64

In [ ]:
# 22
df.groupby("type").size()

type
Movie      6131
TV Show    2676
dtype: int64

In [ ]:
# 24
df["country"].value_counts().head(3)

country
United States    2818
India             972
unknown           831
Name: count, dtype: int64

In [ ]:
# 25
df[df["type"]=="TV Show"].groupby(df["date_added"].dt.year).size()

date_added
2008.0      1
2013.0      5
2014.0      5
2015.0     26
2016.0    176
2017.0    349
2018.0    412
2019.0    592
2020.0    595
2021.0    505
dtype: int64

In [ ]:
# 26
df[df["director"].str.contains("Martin", case=False, na=False)]

,show_id,type,title,director,cast,country,date_added,release_year,rating,duration,listed_in,description,year_added,month_name
143,s144,Movie,Green Lantern,Martin Campbell,"Ryan Reynolds, Blake Lively, Peter Sarsgaard, ...",United States,2021-09-01,2011,PG-13,114 min,"Action & Adventure, Sci-Fi & Fantasy",Test pilot Hal Jordan harnesses glowing new po...,2021.0,September
149,s150,Movie,I Got the Hook Up,Michael Martin,"Master P, Anthony Johnson, Gretchen Palmer, Fr...",United States,2021-09-01,1998,R,93 min,"Action & Adventure, Comedies",After getting their hands on a misdirected shi...,2021.0,September
579,s580,Movie,Midnight Run,Martin Brest,"Robert De Niro, Charles Grodin, Yaphet Kotto, ...",United States,2021-07-01,1988,R,126 min,"Action & Adventure, Classic Movies, Comedies",A cop-turned-bounty hunter runs into trouble a...,2021.0,July
903,s904,Movie,Nayattu,Martin Prakkat,"Kunchacko Boban, Joju George, Nimisha Sajayan,...",India,2021-05-09,2021,TV-MA,122 min,"Dramas, International Movies, Thrillers",Three police officers become pawns for unscrup...,2021.0,May
944,s945,Movie,S.M.A.R.T Chase,Charles Martin,"Orlando Bloom, Leo Wu, Simon Yam, Hannah Quinl...",China,2021-05-01,2018,TV-MA,94 min,Action & Adventure,A disgraced security agent who specializes in ...,2021.0,May
1089,s1090,Movie,Two Distant Strangers,"Travon Free, Martin Desmond Roe","Joey Bada$$, Andrew Howard, Zaria",United States,2021-04-09,2021,TV-MA,32 min,Dramas,"In this Oscar-nominated short film, a man tryi...",2021.0,April
1358,s1359,Movie,Shutter Island,Martin Scorsese,"Leonardo DiCaprio, Mark Ruffalo, Ben Kingsley,...",United States,2021-02-01,2010,R,139 min,Thrillers,A U.S. marshal's troubling visions compromise ...,2021.0,February
1642,s1643,Movie,The Beast,Ludovico Di Martino,"Fabrizio Gifuni, Lino Musella, Monica Piseddu,...",Italy,2020-11-27,2020,TV-MA,100 min,"Action & Adventure, International Movies","To rescue his daughter, an unstable Special Fo...",2020.0,November
1736,s1737,Movie,Operation Christmas Drop,Martin Wood,"Kat Graham, Alexander Ludwig, Virginia Madsen,...",United States,2020-11-05,2020,TV-G,96 min,"Children & Family Movies, Comedies, Romantic M...",A by-the-book political aide falls for a big-h...,2020.0,November
2632,s2633,Movie,No Direction Home: Bob Dylan,Martin Scorsese,"Bob Dylan, Joan Baez, Dave Van Ronk, Peter Yar...","United Kingdom, United States, Japan",2020-04-25,2005,TV-MA,208 min,"Documentaries, Music & Musicals",Featuring rare concert footage and interviews ...,2020.0,April
2860,s2861,Movie,Hugo,Martin Scorsese,"Ben Kingsley, Sacha Baron Cohen, Asa Butterfie...","United Kingdom, United States, France",2020-03-01,2011,PG,127 min,"Children & Family Movies, Dramas","Living inside a Paris train station, an orphan...",2020.0,March
3227,s3228,Movie,The Irishman,Martin Scorsese,"Robert De Niro, Al Pacino, Joe Pesci, Harvey K...",United States,2019-11-27,2019,R,209 min,Dramas,Hit man Frank Sheeran looks back at the secret...,2019.0,November
3646,s3647,Movie,Demetri Martin: The Overthinker,"Jay Karas, Demetri Martin",Demetri Martin,United States,2019-07-21,2018,TV-MA,56 min,Stand-Up Comedy,"With his signature one-liners and drawings, De...",2019.0,July
3759,s3760,Movie,Rolling Thunder Revue: A Bob Dylan Story by Ma...,Martin Scorsese,"Bob Dylan, Allen Ginsberg, Joan Baez, Patti Sm...",United States,2019-06-12,2019,TV-MA,142 min,"Documentaries, Music & Musicals","In an alchemic mix of fact and fantasy, Martin...",2019.0,June
4993,s4994,Movie,The Outsider,Martin Zandvliet,"Jared Leto, Tadanobu Asano, Kippei Shiina, Shi...",United States,2018-03-09,2018,TV-MA,121 min,"Dramas, Thrillers",An American soldier imprisoned in postwar Japa...,2018.0,March
5068,s5069,Movie,Countdown to Death: Pablo Escobar,"Santiago Diaz, Pablo Martin Farina",NaN,unknown,2018-01-22,2017,TV-MA,69 min,"Documentaries, International Movies","Through rare interviews, images and wiretap au...",2018.0,January
5249,s5250,Movie,Verónica,"Carlos Algara, Alejandro Martinez-Beltran","Arcelia Ramírez, Olga Segura, Sofía Garza",Mexico,2017-10-01,2017,TV-MA,81 min,"Dramas, Independent Movies, International Movies",A reclusive psychologist agrees to treat a pat...,2017.0,October
5322,s5323,Movie,Undefeated,"Daniel Lindsay, T.J. Martin","Montrail 'Money' Brown, O.C. Brown, Bill Court...",United States,2017-08-18,2011,PG-13,113 min,"Documentaries, Sports Movies",An inspirational profile of an inner-city high...,2017.0,August
5824,s5825,Movie,Interview with a Serial Killer,Christopher Martin,Arthur Shawcross,United States,2016-08-01,2008,TV-MA,45 min,Documentaries,"In this jailhouse interview, Arthur Shawcross,...",2016.0,August
6060,s6061,Movie,A Thin Line Between Love & Hate,Martin Lawrence,"Martin Lawrence, Lynn Whitfield, Regina King, ...",United States,2020-12-01,1996,R,108 min,"Comedies, Romantic Movies",When a philandering club promoter sets out to ...,2020.0,December
6111,s6112,Movie,Alice Doesn't Live Here Anymore,Martin Scorsese,"Ellen Burstyn, Kris Kristofferson, Billy Green...",United States,2019-07-01,1974,PG,112 min,"Classic Movies, Comedies, Dramas",A widowed singer and single mother starts over...,2019.0,July
6306,s6307,Movie,Big Kill,Scott Martin,"Christoph Sanders, Jason Patric, Clint Glenn H...",United States,2019-06-18,2018,R,126 min,Action & Adventure,A tenderfoot and two gamblers seeking their fo...,2019.0,June
6328,s6329,Movie,Black Snow,Martin Hodara,"Ricardo Darín, Leonardo Sbaraglia, Laia Costa,...","Argentina, Spain",2017-07-01,2017,TV-MA,91 min,"Dramas, International Movies, Thrillers",An old tragedy and lingering animosity erupt w...,2017.0,July
6427,s6428,Movie,Casino Royale,Martin Campbell,"Daniel Craig, Judi Dench, Eva Green, Jeffrey W...","United Kingdom, Czech Republic, United States,...",2020-08-31,2006,PG-13,145 min,Action & Adventure,Daniel Craig makes his debut as the newly mint...,2020.0,August
6435,s6436,Movie,Cave,Henrik Martin Dahlsbakken,"Heidi Toini, Benjamin Helstad, Mads Sjogard Pe...",Norway,2017-06-15,2016,TV-MA,77 min,"Action & Adventure, International Movies, Thri...",Torn between old camaraderie and recent tensio...,2017.0,June
6579,s6580,Movie,Dean,Demetri Martin,"Demetri Martin, Kevin Kline, Gillian Jacobs, R...",United States,2020-03-15,2016,PG-13,94 min,"Comedies, Dramas, Independent Movies","As his father takes steps to move on, a New Yo...",2020.0,March
6622,s6623,Movie,Dolphin Tale 2,Charles Martin Smith,"Morgan Freeman, Ashley Judd, Harry Connick Jr....",United States,2019-02-25,2014,PG,107 min,"Children & Family Movies, Dramas","Winter the dolphin, who survived a tragic inju...",2019.0,February
6826,s6827,Movie,Gangs of New York,Martin Scorsese,"Leonardo DiCaprio, Daniel Day-Lewis, Cameron D...","United States, Italy",2019-08-20,2002,R,167 min,Dramas,In the crime-ridden slums of New York in the 1...,2019.0,August
6866,s6867,Movie,GoldenEye,Martin Campbell,"Pierce Brosnan, Sean Bean, Izabella Scorupco, ...","United Kingdom, United States",2019-12-31,1995,PG-13,130 min,Action & Adventure,Pierce Brosnan takes his first turn as debonai...,2019.0,December
6880,s6881,Movie,GoodFellas,Martin Scorsese,"Robert De Niro, Ray Liotta, Joe Pesci, Lorrain...",United States,2021-01-01,1990,R,145 min,"Classic Movies, Dramas",Former mobster Henry Hill recounts his colorfu...,2021.0,January
6915,s6916,Movie,Hangman,Johnny Martin,"Al Pacino, Karl Urban, Brittany Snow, Joe Ande...",United States,2020-05-06,2017,R,99 min,Thrillers,"A homicide detective, a criminal profiler and ...",2020.0,May
6940,s6941,Movie,Have You Seen the Listers?,Eddie Martin,Anthony Lister,Australia,2019-02-01,2017,TV-MA,86 min,"Documentaries, International Movies",This documentary paints a candid picture of Au...,2019.0,February
7015,s7016,Movie,How to Be a Player,Lionel C. Martin,"Bill Bellamy, Natalie Desselle, Lark Voorhies,...",United States,2019-11-01,1997,R,94 min,Comedies,Dray lives life one woman at a time and is the...,2019.0,November
7251,s7252,Movie,LA 92,"Daniel Lindsay, T.J. Martin",NaN,United States,2018-03-01,2017,R,114 min,Documentaries,Previously unseen footage is shaped into a fre...,2018.0,March
7431,s7432,Movie,Mean Streets,Martin Scorsese,"Robert De Niro, Harvey Keitel, David Proval, A...",United States,2019-07-01,1973,R,112 min,"Classic Movies, Dramas, Independent Movies","In New York's Little Italy, a low-level hoodlu...",2019.0,July
7482,s7483,Movie,Money,Martin Rosete,"Kellan Lutz, Jess Weixler, Jesse Williams, Jam...","United States, Spain",2017-10-15,2016,R,84 min,Thrillers,Two corporate spies with a $5 million haul for...,2017.0,October
7601,s7602,Movie,NOVA: Building Chernobyl's MegaTomb,Martin Gorst,Eric Meyers,United States,2019-07-01,2017,TV-PG,53 min,Documentaries,Thirty years after Chernobyl’s nuclear disaste...,2019.0,July
7606,s7607,Movie,NOVA: Eclipse Over America,Martin Gorst,NaN,United States,2019-07-01,2017,TV-G,53 min,Documentaries,Scientists reveal how the 2017 solar eclipse p...,2019.0,July
7820,s7821,Movie,Raging Bull,Martin Scorsese,"Robert De Niro, Cathy Moriarty, Joe Pesci, Fra...",United States,2019-10-01,1980,R,129 min,"Classic Movies, Dramas, Sports Movies",This gritty biopic of brutal boxer Jake LaMott...,2019.0,October
7990,s7991,Movie,SGT. Will Gardner,Max Martini,"Max Martini, Omari Hardwick, Lily Rabe, Elisab...",United States,2019-05-19,2019,TV-MA,125 min,Dramas,A homeless vet who has PTSD steals a motorcycl...,2019.0,May
8272,s8273,Movie,The Departed,Martin Scorsese,"Leonardo DiCaprio, Matt Damon, Jack Nicholson,...","United States, Hong Kong",2021-01-01,2006,R,151 min,"Dramas, Thrillers",Two rookie Boston cops are sent deep undercove...,2021.0,January
8309,s8310,Movie,The Foreigner,Martin Campbell,"Pierce Brosnan, Katie Leung, Manolo Cardona, C...","United Kingdom, China, United States, India",2020-02-14,2017,R,113 min,"Action & Adventure, International Movies","After his daughter is killed by terrorists, a ...",2020.0,February
8413,s8414,Movie,The Mask of Zorro,Martin Campbell,"Antonio Banderas, Anthony Hopkins, Catherine Z...","United States, Germany, Mexico",2020-01-01,1998,PG-13,138 min,"Action & Adventure, Romantic Movies",An aging Zorro passes the torch to a young suc...,2020.0,January
8735,s8736,Movie,Who's That Knocking at My Door?,Martin Scorsese,"Zina Bethune, Harvey Keitel, Anne Collette, Le...",United States,2019-07-01,1967,R,90 min,"Classic Movies, Dramas, Independent Movies",A woman's revelation that she was once raped s...,2019.0,July

In [ ]:
# 27
df["first_actor"] = df["cast"].str.split(",").str[0]

In [ ]:
# 28
df[df["listed_in"].str.contains("Comedy")].shape[0]

399

In [ ]:
# 29
df["title_length"] = df["title"].str.len()

In [ ]:
# 30
df["listed_in"] = df["listed_in"].str.lower()

In [ ]:

# 31
df.sort_values("release_year", ascending=False)

,show_id,type,title,director,cast,country,date_added,release_year,rating,duration,listed_in,description,year_added,month_name,first_actor,title_length
1,s2,TV Show,Blood & Water,NaN,"Ama Qamata, Khosi Ngema, Gail Mabalane, Thaban...",South Africa,2021-09-24,2021,TV-MA,2 Seasons,"international tv shows, tv dramas, tv mysteries","After crossing paths at a party, a Cape Town t...",2021.0,September,Ama Qamata,13
2,s3,TV Show,Ganglands,Julien Leclercq,"Sami Bouajila, Tracy Gotoas, Samuel Jouy, Nabi...",unknown,2021-09-24,2021,TV-MA,1 Season,"crime tv shows, international tv shows, tv act...",To protect his family from a powerful drug lor...,2021.0,September,Sami Bouajila,9
3,s4,TV Show,Jailbirds New Orleans,NaN,NaN,unknown,2021-09-24,2021,TV-MA,1 Season,"docuseries, reality tv","Feuds, flirtations and toilet talk go down amo...",2021.0,September,NaN,21
31,s32,TV Show,Chicago Party Aunt,NaN,"Lauren Ash, Rory O'Malley, RuPaul Charles, Jil...",unknown,2021-09-17,2021,TV-MA,1 Season,tv comedies,Chicago Party Aunt Diane is an idolized troubl...,2021.0,September,Lauren Ash,18
30,s31,Movie,Ankahi Kahaniya,"Ashwiny Iyer Tiwari, Abhishek Chaubey, Saket C...","Abhishek Banerjee, Rinku Rajguru, Delzad Hiwal...",unknown,2021-09-17,2021,TV-14,111 min,"dramas, independent movies, international movies","As big city life buzzes around them, lonely so...",2021.0,September,Abhishek Banerjee,15
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
8739,s8740,Movie,Why We Fight: The Battle of Russia,"Frank Capra, Anatole Litvak",NaN,United States,2017-03-31,1943,TV-PG,82 min,documentaries,This installment of Frank Capra's acclaimed do...,2017.0,March,NaN,34
8660,s8661,Movie,Undercover: How to Operate Behind Enemy Lines,John Ford,NaN,United States,2017-03-31,1943,TV-PG,61 min,"classic movies, documentaries",This World War II-era training film dramatizes...,2017.0,March,NaN,45
7790,s7791,Movie,Prelude to War,Frank Capra,NaN,United States,2017-03-31,1942,TV-14,52 min,"classic movies, documentaries",Frank Capra's documentary chronicles the rise ...,2017.0,March,NaN,14
8205,s8206,Movie,The Battle of Midway,John Ford,"Henry Fonda, Jane Darwell",United States,2017-03-31,1942,TV-14,18 min,"classic movies, documentaries",Director John Ford captures combat footage of ...,2017.0,March,Henry Fonda,20
4250,s4251,TV Show,Pioneers: First Women Filmmakers*,NaN,NaN,unknown,2018-12-30,1925,TV-14,1 Season,tv shows,This collection restores films from women who ...,2018.0,December,NaN,33

In [ ]:
#32
df["release_year"].min()
df["release_year"].max()

2021

In [ ]:
# 33
df.sort_values("title")[["title"]].head()

                              title
2036                         #Alive
2304  #AnneFrank - Parallel Stories
2481              #FriendButMarried
2324            #FriendButMarried 2
5973                          #Roxy

In [ ]:
# 34
df.set_index("show_id", inplace=True)

In [ ]:
# 35
df.reset_index(inplace=True)

In [ ]:
# 36
df["content_age"] = 2024 - df["release_year"]

In [ ]:
# 37
df["is_movie"] = df["type"] == "Movie"

In [ ]:
# 42
df[(df["director"]=="Christopher Nolan") &
   (df["country"].str.contains("United States", na=False))]

,show_id,type,title,director,cast,country,date_added,release_year,rating,duration,listed_in,description,year_added,month_name,first_actor,title_length,content_age,is_movie
340,s341,Movie,Inception,Christopher Nolan,"Leonardo DiCaprio, Joseph Gordon-Levitt, Ellio...","United States, United Kingdom",2021-08-01,2010,PG-13,148 min,"action & adventure, sci-fi & fantasy, thrillers",A troubled thief who extracts secrets from peo...,2021.0,August,Leonardo DiCaprio,9,14,True

In [ ]:
43
df[(df["listed_in"].str.contains("Drama|Thriller", case=False, na=False)) &
   (df["release_year"]==2021)]

,show_id,type,title,director,cast,country,date_added,release_year,rating,duration,listed_in,description,year_added,month_name,first_actor,title_length,content_age,is_movie
1,s2,TV Show,Blood & Water,NaN,"Ama Qamata, Khosi Ngema, Gail Mabalane, Thaban...",South Africa,2021-09-24,2021,TV-MA,2 Seasons,"international tv shows, tv dramas, tv mysteries","After crossing paths at a party, a Cape Town t...",2021.0,September,Ama Qamata,13,3,False
5,s6,TV Show,Midnight Mass,Mike Flanagan,"Kate Siegel, Zach Gilford, Hamish Linklater, H...",unknown,2021-09-24,2021,TV-MA,1 Season,"tv dramas, tv horror, tv mysteries",The arrival of a charismatic young priest brin...,2021.0,September,Kate Siegel,13,3,False
9,s10,Movie,The Starling,Theodore Melfi,"Melissa McCarthy, Chris O'Dowd, Kevin Kline, T...",United States,2021-09-24,2021,PG-13,104 min,"comedies, dramas",A woman adjusting to life after a loss contend...,2021.0,September,Melissa McCarthy,12,3,True
12,s13,Movie,Je Suis Karl,Christian Schwochow,"Luna Wedler, Jannis Niewöhner, Milan Peschel, ...","Germany, Czech Republic",2021-09-23,2021,TV-MA,127 min,"dramas, international movies",After most of her family is murdered in a terr...,2021.0,September,Luna Wedler,12,3,True
15,s16,TV Show,Dear White People,NaN,"Logan Browning, Brandon P. Bell, DeRon Horton,...",United States,2021-09-22,2021,TV-MA,4 Seasons,"tv comedies, tv dramas",Students of color navigate the daily slights a...,2021.0,September,Logan Browning,17,3,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1410,s1411,Movie,Tribhanga - Tedhi Medhi Crazy,Renuka Shahane,"Kajol, Tanvi Azmi, Mithila Palkar, Kunaal Roy ...",India,2021-01-15,2021,TV-MA,96 min,"dramas, international movies","When her estranged mother falls into a coma, a...",2021.0,January,Kajol,29,3,True
1412,s1413,Movie,Wish You,Sung Do-jun,"Kang In-soo, Lee Sang, Soo-bin",South Korea,2021-01-15,2021,TV-PG,102 min,"dramas, international movies, lgbtq movies","Singing and dreaming together, a talented sing...",2021.0,January,Kang In-soo,8,3,True
1431,s1432,Movie,Stuck Apart,NaN,"Engin Günaydın, Haluk Bilginer, Binnur Kaya, Ö...",Turkey,2021-01-08,2021,TV-MA,97 min,"comedies, dramas, international movies","Entrenched in a midlife crisis, Aziz seeks sol...",2021.0,January,Engin Günaydın,11,3,True
1448,s1449,TV Show,Cobra Kai,NaN,"Ralph Macchio, William Zabka, Xolo Maridueña, ...",United States,2021-01-01,2021,TV-14,3 Seasons,"tv action & adventure, tv comedies, tv dramas",Decades after the tournament that changed thei...,2021.0,January,Ralph Macchio,9,3,False
1460,s1461,TV Show,Monarca,NaN,"Irene Azuela, Juan Manuel Bernal, Osvaldo Bena...",Mexico,2021-01-01,2021,TV-MA,2 Seasons,"international tv shows, spanish-language tv sh...","After 20 years, Ana María returns to Mexico an...",2021.0,January,Irene Azuela,7,3,False

In [ ]:
# 44
df[df["cast"].str.contains("Tom Hanks", case=False, na=False)].shape[0]

8

In [ ]:
# 45
df["listed_in"].str.split(", ").explode().value_counts().max()

2752

In [ ]:
# 46
df.groupby(["rating","type"]).size()

rating    type
66 min    Movie         1
74 min    Movie         1
84 min    Movie         1
G         Movie        41
NC-17     Movie         3
NR        Movie        75
          TV Show       5
PG        Movie       287
PG-13     Movie       490
R         Movie       797
          TV Show       2
TV-14     Movie      1427
          TV Show     733
TV-G      Movie       126
          TV Show      94
TV-MA     Movie      2062
          TV Show    1145
TV-PG     Movie       540
          TV Show     323
TV-Y      Movie       131
          TV Show     176
TV-Y7     Movie       139
          TV Show     195
TV-Y7-FV  Movie         5
          TV Show       1
UR        Movie         3
dtype: int64

In [ ]:
# 47
df[(df["date_added"].dt.month==1) &
   (df["release_year"]<2010)]

,show_id,type,title,director,cast,country,date_added,release_year,rating,duration,listed_in,description,year_added,month_name,first_actor,title_length,content_age,is_movie
1422,s1423,Movie,Apaharan,Prakash Jha,"Ajay Devgn, Nana Patekar, Bipasha Basu, Ayub K...",India,2021-01-08,2005,TV-14,161 min,"dramas, international movies",Raised under the condescending eye of his acti...,2021.0,January,Ajay Devgn,8,19,True
1423,s1424,Movie,BluffMaster!,Rohan Sippy,"Abhishek Bachchan, Priyanka Chopra, Riteish De...",India,2021-01-08,2005,TV-14,129 min,"comedies, international movies, romantic movies",When his girlfriend learns the truth about his...,2021.0,January,Abhishek Bachchan,12,19,True
1426,s1427,Movie,Gangaajal,Prakash Jha,"Ajay Devgn, Gracy Singh, Mohan Agashe, Mohan J...",India,2021-01-08,2003,TV-MA,148 min,"dramas, international movies","Posted to a small, crime-ridden town, a cop so...",2021.0,January,Ajay Devgn,9,21,True
1441,s1442,Movie,Hello Brother,Sohail Khan,"Salman Khan, Arbaaz Khan, Rani Mukerji, Johny ...",India,2021-01-04,1999,TV-14,126 min,"action & adventure, comedies, international mo...",After receiving a heart transplant from a murd...,2021.0,January,Salman Khan,13,25,True
1447,s1448,Movie,Case 39,Christian Alvart,"Renée Zellweger, Jodelle Ferland, Ian McShane,...","United States, Canada",2021-01-01,2009,R,111 min,"horror movies, thrillers",A naïve social worker brings a 10-year-old chi...,2021.0,January,Renée Zellweger,7,15,True
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
8764,s8765,Movie,Wyatt Earp,Lawrence Kasdan,"Kevin Costner, Dennis Quaid, Gene Hackman, Dav...",United States,2020-01-01,1994,PG-13,191 min,action & adventure,Legendary lawman Wyatt Earp is continually at ...,2020.0,January,Kevin Costner,10,30,True
8766,s8767,Movie,XXx,Rob Cohen,"Vin Diesel, Asia Argento, Marton Csokas, Samue...",United States,2019-01-01,2002,PG-13,124 min,"action & adventure, sports movies",A notorious underground rush-seeker deemed unt...,2019.0,January,Vin Diesel,3,22,True
8767,s8768,Movie,XXX: State of the Union,Lee Tamahori,"Ice Cube, Samuel L. Jackson, Willem Dafoe, Sco...",United States,2019-01-01,2005,PG-13,101 min,action & adventure,"In this action-packed follow-up to XXX, U.S. i...",2019.0,January,Ice Cube,23,19,True
8773,s8774,Movie,Yanda Kartavya Aahe,Kedar Shinde,"Ankush Choudhary, Smita Shewale, Mohan Joshi, ...",India,2018-01-01,2006,TV-PG,151 min,"comedies, dramas, international movies",Thanks to an arranged marriage that was design...,2018.0,January,Ankush Choudhary,19,18,True
8805,s8806,Movie,Zoom,Peter Hewitt,"Tim Allen, Courteney Cox, Chevy Chase, Kate Ma...",United States,2020-01-11,2006,PG,88 min,"children & family movies, comedies","Dragged from civilian life, a former superhero...",2020.0,January,Tim Allen,4,18,True

In [ ]:

# 48
(df.isnull().sum()/len(df))*100

show_id          0.000000
type             0.000000
title            0.000000
director        29.908028
cast             9.367549
country          0.000000
date_added       0.113546
release_year     0.000000
rating           0.045418
duration         0.034064
listed_in        0.000000
description      0.000000
year_added       0.113546
month_name       0.113546
first_actor      9.367549
title_length     0.000000
content_age      0.000000
is_movie         0.000000
dtype: float64

In [ ]:
# 49
df["director"].value_counts().head()

director
Rajiv Chilaka             19
Raúl Campos, Jan Suter    18
Suhas Kadav               16
Marcus Raboy              16
Jay Karas                 14
Name: count, dtype: int64